### ISSUE TITLE
Any Alternatives ?

### ISSUE THREAD

**Issue by Nuture-blip** [ClickNinYT/BlueSky#4]
Any alternatives ?

**Comment by Temder** [comment]
The only alternatives I know and have used are BLauncher and a launcher from online-fix.me.

**Comment by Nuture-blip** [comment]
@Temder Is BlueSky safe to download :/

**Comment by Temder** [comment]
BlueSky doesn't contain any viruses but as stated on this github it is still illegal because you don't pay for playing minecraft

**Comment by Temder** [comment]
I think that BlueSky is safer to use than the launcher on the online-fix.me site

**Comment by Temder** [comment]
> @Temder Is BlueSky safe to download :/
> https://www.virustotal.com/gui/file/ad4a2ee5e73580f2106cab993cfcc26f97d271927d9e0d69e4a2ff0e46009bf6

These are false positives. You can join the discord server to get a better explanation.

**Comment by ClickNinYT** [comment]
Please join our Discord server to get a more detailed explaination.
https://discord.gg/cSvj4YFUSn

Or, I can explain in a basic way.
In BlueSkyAPI we have a function called DLLInject() which allow injecting DLLs into Minecraft, this particular function triggers a lot of anti virus and thus causing the false positive as shown, as it often used in malware/adware. BlueSky is in rewrite at the moment so I will try to make it more AV friendly.
